---
unicornVersion: "0.1.0"
name: "hpi_flutter"
description: "The official HPI app, written in Flutter"
license: null
version: "0.3.5"
categorization:
  component:
    values:
      - name: "app"
        description: "app module"
        paths:
          - "lib/app/**"
      - name: "core"
        description: "core module"
        paths:
          - "lib/core/**"
      - name: "course"
        description: "course module"
        paths:
          - "lib/course/**"
      - name: "crashreporting"
        description: "crashreporting module"
        paths:
          - "lib/crashreporting/**"
      - name: "feedback"
        description: "feedback module"
        paths:
          - "lib/feedback/**"
      - name: "food"
        description: "food module"
        paths:
          - "lib/food/**"
      - name: "myhpi"
        description: "myhpi module"
        paths:
          - "lib/core/**"
      - name: "news"
        description: "news module"
        paths:
          - "lib/news/**"
      - name: "onboarding"
        description: "onboarding module"
        paths:
          - "lib/onboarding/**"
      - name: "openhpi"
        description: "openhpi module"
        paths:
          - "lib/openhpi/**"
      - name: "settings"
        description: "settings module"
        paths:
          - "lib/settings/**"
      - name: "tools"
        description: "tools module"
        paths:
          - "lib/tools/**"
    labels:
      color: "c2e0c6"
      prefix: "C: "
      descriptionPrefix: "Component: "
  priority:
    values:
      - name: "1"
        description: "1 (Lowest)"
      - name: "2"
        description: "2 (Low)"
      - name: "3"
        description: "3 (Medium)"
      - name: "4"
        description: "4 (High)"
      - name: "5"
        description: "5 (Highest)"
    labels:
      color: "e5b5ff"
      prefix: "P: "
      descriptionPrefix: "Priority: "
  type:
    values:
      - name: "feat"
        description: ":tada: New Features"
      - name: "change"
        description: "⚡ Changes"
      - name: "fix"
        description: ":bug: Bug Fixes"
      - name: "docs"
        description: ":scroll: Documentation updates"
      - name: "refactor"
        description: ":building_construction: Refactoring"
      - name: "build"
        description: ":package: Build, CI & other meta changes"
    labels:
      color: "c5def5"
      prefix: "T: "
      descriptionPrefix: "Type: "
