include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/core/hpi_icons.dart
    - lib/hpi_cloud_apis/**
    - lib/**/*.g.dart
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - camel_case_types
