name: hpi_flutter
description: The official HPI app, written in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General
  kt_dart: ^0.6.2

  # Data
  protobuf: ^0.13.15
  grpc: ^2.0.0+1
  rxdart: ^0.22.1+1
  provider: ^3.0.0+1
  http: ^0.12.0+2

  # UI
  intl: ^0.15.8
  timeago: ^2.0.18
  url_launcher: ^5.1.2
  align_positioned: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
