name: hpi_flutter
description: The official HPI app, written in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General
  kt_dart: ^0.6.2

  # Data
  protobuf: ^1.0.0
  immutable_proto: ^0.0.4
  grpc: ^2.1.2
  rxdart: ^0.22.1+1
  provider: ^3.0.0+1
  http: ^0.12.0+2
  yaml: ^2.1.16
  shared_preferences: ^0.5.3+4
  package_info: ^0.4.0+6

  # UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  sprintf: ^4.0.2
  flutter_html: ^0.10.4
  timeago: ^2.0.18
  outline_material_icons: ^0.1.0
  url_launcher: ^5.1.2
  align_positioned: ^1.0.8
  cached_network_image: ^1.1.1
  screenshot: ^0.1.1
  flutter_pagewise: ^1.2.3
  flutter_markdown: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  immutable_proto_generator: ^0.0.4

  flutter_launcher_icons: ^0.7.2+1


flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png # colored logo
    - assets/logo/logo_text.png # colored logo with gray text
    - assets/logo/logo_captionWhite.png # colored logo with white text and caption
    - assets/logo/mobileDev sheep.png
    - assets/images/onboarding/mrNet.png
    - assets/localizations/strings_de.yaml
    - assets/localizations/strings_en.yaml
    - assets/privacyPolicy.md

  fonts:
  - family: HpiIcons
    fonts:
      - asset: fonts/HpiIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/foreground.png"
