name: hpi_flutter
description: The official HPI app, written in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General
  kt_dart: ^0.6.2
  flutter_localizations:
    sdk: flutter

  # Data
  protobuf: ^0.13.15
  grpc: ^2.0.0+1
  rxdart: ^0.22.1+1
  provider: ^3.0.0+1
  http: ^0.12.0+2
  yaml: ^2.1.16

  # UI
  intl: ^0.16.0
  flutter_html: ^0.10.4
  timeago: ^2.0.18
  outline_material_icons: ^0.1.0
  url_launcher: ^5.1.2
  fluttery: ^0.0.8
  align_positioned: ^1.0.8
  cached_network_image: ^1.1.1
  screenshot: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1


flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo_text.png
    - assets/localizations/strings_de.yaml
    - assets/localizations/strings_en.yaml

  fonts:
  - family:  HpiIcons
    fonts:
      - asset: fonts/HpiIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/foreground.png"
