/// Flutter icons HpiIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HpiIcons
///      fonts:
///       - asset: fonts/HpiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HpiIcons {
  HpiIcons._();

  static const _kFontFam = 'HpiIcons';

  static const IconData newspaper = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData myhpi = const IconData(0xe801, fontFamily: _kFontFam);
}
