name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup
      uses: ./.github/workflows/setup

    - name: Build apk
      run: flutter build apk
