name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Install Flutter (beta)
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
        flutter-version: '1.10.7'
    - name: Install dependencies
      run: flutter pub get

    - name: Create temp dir
      run: mkdir ./temp
    - name: Download HPI Cloud APIs
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HPI-de/hpi-cloud-apis
        tag: '0.0.11'
        path: ./temp
        file: generated-dart.zip
    - name: Unzip HPI Cloud APIs
      run: unzip ./temp/generated-dart.zip -d ./lib
    - name: Delete temp dir
      run: rm -r ./temp

    - name: Run code generator(s)
      run: flutter pub run build_runner build

    - name: Run linter
      run: flutter analyze --write=./flutter_analyze_report.txt
      continue-on-error: true

    - name: Install ruby
      uses: actions/setup-ruby@v1
      if: github.event_name == 'pull_request'
      with:
        ruby-version: '2.6'
    - run: bundle install --without documentation
    - name: Run danger on generated report
      uses: MeilCli/danger-action@v1
      if: github.event_name == 'pull_request'
      with:
        danger_file: Dangerfile
        danger_id: 'danger-pr'
