name: PR

on: [pull_request]

jobs:
  add-type-labels:
    name: Add type labels
    runs-on: ubuntu-latest
    steps:
    - uses: srvaroa/labeler@master
      with:
        config_path: .github/type-labels.yml
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  add-component-labels:
    name: Add component labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        configuration-path: .github/component-labels.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  assign-author:
    name: Assign author
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
    - uses: samspills/assign-pr-to-author@v1.0
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'

  title-lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '^(?<type>build|chore|ci|docs|feat|fix|refactor)(?:\((?<scopes>(?:\w|(?<=\w)\/(?=\w))+?(?:,\s*(?:\w|(?<=\w)\/(?=\w))+?)*?)\))?: \s*(?<description>.*?)\s*$'
